### PR TITLE
General cleanup in HTML document

### PR DESCRIPTION
**Pull request by djangokillen**
As a general rule of thumb you should have the scripts in the bottom of the body, not in the head. If you want to, you can also wrap your design.js document into a $(document).ready(function() {});

I added a meta charset UTF 8, deleted some blank space and added some new rows so it is easier to read (imo).

Also; why do you have such a low version of jQuery? And why are you not using some CDN that's faster, like Google's?

### CODE REVIEW

**Comment by djangokillen** [comment]
I understand if you think this PR is completely bollocks, developers opinions are completely different on most of these topics.

**Comment by KlongDor** [comment]
This looks good

**Comment by djangokillen** [comment]
Still, every time I see scripts in the header it makes my eye twitch a little.

**Comment by djangokillen** [comment]
Newest version of jQuery btw:
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

**Comment by djangokillen** [comment]
The newest version of jQuery is <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

**Comment by djangokillen** [comment]
The newest version of jQuery is https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

**Comment by djangokillen** [comment]
You could download it to once again improve the performance a little.

**Comment by KlongDor** [comment]
There may be some sense to this such as some browsers possibly load the scripts before the elements the scripts affect if scripts are in head

**Pull request merged**
